services:
  - type: web
    name: access-control-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
